# Generated by Django 3.1.1 on 2020-09-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='authot',
            new_name='author',
        ),
    ]
